-- This query count the number of customers by the City
SELECT 
    city,
    COUNT(*) AS total_customers
FROM customers_dim
GROUP BY 
    city
ORDER BY 
    total_customers DESC
LIMIT
    3

-- This query count the sum of revenue generated by the menu item
SELECT 
    m.item_name,
    SUM(oi.quantity * m.price) AS total_revenue
FROM 
    order_item_dim oi
JOIN menu_dim m ON oi.item_id = m.item_id
GROUP BY 
    m.item_name
ORDER BY 
    total_revenue DESC